language: php
services:
  - docker

sudo: false

php:
    - 7.2
    - 7.3

env:
  HOST_YVES: localhost
  PORT_YVES: 8085
  HOST_ZED: localhost
  BASE_URL_ZED_API: http://localhost:8086

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - "php -S $HOST_YVES:$PORT_YVES -t tests/App/public/yves &"
    - "php -S $BASE_URL_ZED_API -t tests/App/public/zed &"
    - docker-compose up -d
    - composer install
    - tests/App/bin/console transfer:generate
    - tests/App/bin/console propel:install

script:
    - composer integrate
